### ISSUE TITLE
Mixed Content - Avatars not using SSL path when plugin is active

### ISSUE THREAD

**Issue by affiliatenow** [imath/bp-avatar-suggestions#11]
When I have the plugin active I get the following errors in my browser, which does not allow me to get a "Green" SSL check:
```
Mixed Content: The page at 'https://www.domain.com/' was loaded over HTTPS, but requested an insecure image 'http://www.domain.com/wp-content/uploads/avatar.png'. This content should also be served over HTTPS.
(index):742 Mixed Content: The page at 'https://www.domain.com/' was loaded over HTTPS, but requested an insecure image 'http://www.domain.com/wp-content/uploads/avatar.png'. This content should also be served over HTTPS.
```

Once I disable the plugin everything is fine... when I look at the files in my media folder they are using https://

**Comment by imath** [comment]
Hi thanks for your feedback and sorry for this issue.

I'm going to need your help here. I've prepared a patch but i'm not sure it's enough.
https://gist.github.com/imath/8eee57503824fb880a11

Are you able to patch the ```includes/bp-avatar-suggestions-front.php``` file ? else i'll need send you this file with the applied patch.

Once applied, you'll need to check everything is ok in front end and in back end > Administration > Settings > BuddyPress > Avatar Suggestions

**Comment by imath** [comment]
I've tested over https and it's working fine.
