### ISSUE TITLE
Avatar suggestions not show in front-end

### ISSUE THREAD

**Issue by filetopaixao** [imath/bp-avatar-suggestions#12]
wordpress 4.1.1
buddypress 2.2.2.1
bp-avatar-suggestion 1.2.0

the suggestions images will not appear on the front end even with the user without avatar in the profile. How to solve?

**Comment by imath** [comment]
Do you use Jetpack ?

It looks like the problem is the thumbnail size of the suggestions uploaded are not available causing a javascript error.

**Comment by imath** [comment]
else see : https://wordpress.org/support/topic/does-not-display-avatar-suggestions-on-front-end?replies=4#post-6848469

**Comment by paudelvinay** [comment]
I have the same issue. and it shows Uncaught TypeError: Cannot read property 'url' of undefined.
I have only plugin buddypress(with version  2.2.3.1) and default theme is twenty fifteen.

**Comment by paudelvinay** [comment]
thanks, I have solved the issue. it was due to image size. I have uploaded bigger image and the issue is solved.

**Comment by imath** [comment]
Interesting, thanks a lot @paudelvinay for sharing this info. That's something i haven't thought of. Uploading an image smaller than the thumbnail size e.g. 150x150, is generating an error.. I'll check this and try to include some warnings so that you know quickly something will go wrong :)

**Comment by majiix** [comment]
Hi
I have this issue too. I'm using wplms theme and the avatars are not showing in the front-end.
What's the solution?

**Comment by imath** [comment]
What is the width and the height of your image ? What is the WordPress thumbnail size ?

imath.
http://profiles.wordpress.org/imath/

**Comment by imath** [comment]
@majiix 

Can you delete all your suggestions and try with this image, it has nothing particular except the fact its width and height are > 150px

![icon-300x300](https://cloud.githubusercontent.com/assets/1834524/7666397/3e47b274-fbe4-11e4-994d-2159f7504786.png)

As @paudelvinay said in a previous comment, it can explain the error. You must upload images having width >= thumbnail width and height >= thumbnail height. 150 x 150 px is the default size of WordPress thumbnail.

**Comment by majiix** [comment]
Thank you @imath . Unfortunately this wasn't the solution and didn't work. I think it's because of my theme, because when i changed it to default wordpress theme, the avatar suggestions appeared. such a bad luck that i can't use this plugin.

**Comment by vladimirovii** [comment]
hi
I have it is problem to. as majiix.  
Message:
"You can select one of the suggested avatars below
Click to add or remove the suggested avatar. If a suggestion is selected, you will need to remove it before choosing another one.
Please wait, requesting available suggestions."
and enought.
you pic (url: https://cloud.githubusercontent.com/assets/1834524/7666397/3e47b274-fbe4-11e4-994d-2159f7504786.png) not work to.
fix this?

**Comment by imath** [comment]
Ok. The only way to fix this is to make sure the thumbnail image size is available. Try to change the theme, or deactivate all plugins except BuddyPress and this one to find who's removing the thumbnail size.

imath.
http://profiles.wordpress.org/imath/

**Comment by vladimirovii** [comment]
Thank you. Put a standard theme, it worked!

**Comment by imath** [comment]
What was your theme, i'm curious and would like to understand why it wasnt working.

imath.
http://profiles.wordpress.org/imath/
