### ISSUE TITLE
BP Avatar Suggestions can't add any avatar

### ISSUE THREAD

**Issue by dandyxu** [imath/bp-avatar-suggestions#19]
Hi, imath
     Sorry to bother you and thanks a million for your fantastic plugin - BP Avatar Suggestions. 
     Unfortunately, I met a problem that when I upgraded the WordPress version to 4.4.2, it shows an error like "There was a problem while requesting suggestions.". And at the backend panel, I can't add any new avatars and see the existing avatars.
     So, could you check that, please? I guess that maybe something wrong with compatibility with latest WordPress version. 
     Thanks at advance.

**Comment by imath** [comment]
Thanks for your feedback, i'll check it asap.

**Comment by dandyxu** [comment]
Thanks in advance.

**Comment by imath** [comment]
Hi i've just checked and everything works great for me.

Could it be a problem with another plugin? FYI I'm just using BuddyPress + BP Avatar Suggestions

**Comment by dandyxu** [comment]
Hi, imath
     Thanks for your reply.
     I deactivated all plugins besides BuddyPress + BP Avatar Suggestions, but it still has this error.
     Then, I installed a new site using WordPress 4.4.2 + BuddyPress 2.4.3 + BP Avatar Suggestions 1.3.1 in my local environment. But the same result.
      Please check the screenshot I took. Thanks.
      
![plugin](https://cloud.githubusercontent.com/assets/10475793/13057028/532b6810-d411-11e5-8305-9a61a95c0785.PNG)
![avatar error default](https://cloud.githubusercontent.com/assets/10475793/13057030/587d286c-d411-11e5-9f64-928f777bf129.PNG)

**Comment by imath** [comment]
![avatar-suggestions-ok](https://cloud.githubusercontent.com/assets/1834524/13058367/1774221e-d423-11e5-8677-7878252a82f6.png)

As you can see, it's working fine for me. So unless you give me more information on your config to help me reproduce i don't know what to say...

WordPress > Multisite ?
If so BuddyPress is network activated ?
Else what is the root blog id ?

You can also : 
```php
define( 'WP_DEBUG', true ); 
```
into the wp-config.php of your local environment, then try to see from your browser developer tools what is the reply of the Ajax query.

It can be a filter in a theme, a custom code that is messing with the attachment query

**Comment by dandyxu** [comment]
Hi, imath
Sorry to reply late. Thanks so much for helping.

My current site is not multisite, and the root blog id is #1.
I opened the debug model and also generated debug.log. It seems like that when I added a new suggestion from backend panel, it shows like below:
![upload avatar error](https://cloud.githubusercontent.com/assets/10475793/13074187/03b729c4-d49b-11e5-8777-60e3bdf70480.PNG)
But I checked the media, the image I added has already uploaded successfully indeed.
I uploaded debug.log but it seems very complex to me. So, could you do me a favor to locate where the issue is? 
[debug.txt](https://github.com/imath/bp-avatar-suggestions/files/132316/debug.txt)
Thanks a million.

**Comment by imath** [comment]
It looks like the plugin bp-moderation is generating some errors, could you try to deactivate it to see if it's fixing the issue ?

imath.
http://profiles.wordpress.org/imath/

**Comment by dandyxu** [comment]
Hi,
   I deactivated the bp-moderation plugin but it stills can't work. The screenshots and debug.log are attached below:
![activated plugin](https://cloud.githubusercontent.com/assets/10475793/13076028/45f52c08-d4a7-11e5-8e39-38c9b2b4e04d.PNG)
[debug.txt](https://github.com/imath/bp-avatar-suggestions/files/132417/debug.txt)
Thanks.

**Comment by imath** [comment]
you can set WP_DEBUG back to false.

First there's something using bp_is_front_page() somewhere in your code that shouldn't. I've checked it's not the avatar suggestions plugins. Then it looks like the post object used by the plugin to attach the suggestions is not found, maybe it has been trashed or deleted...

on your local environement try to delete the 'bp-avatar-suggestions-version' option and once done go the Posts administration screen and check if the 'BP Avatar Suggestions required post (do not edit or delete) draft post has been created. If so and try to upload an image to see if it's fixed.

imath.
http://profiles.wordpress.org/imath/

**Comment by dandyxu** [comment]
Hi,
   Thanks again. 
   Well, I'm sorry that I don't know where is the 'bp-avatar-suggestions-version' option. Do you mean that I delete the BP-Avatar_Suggestion Plugin totally? Or I have to edit the database?
And for "Posts administration screen", does it mean this screen?
![avatar backend](https://cloud.githubusercontent.com/assets/10475793/13079255/38f56c8e-d4bb-11e5-948c-90b67ff2eeb3.PNG)
Currently, I can upload image but there is nothing shows in this section. So what can I do now?

Thanks a million.

**Comment by dandyxu** [comment]
Hi, imath
     Thanks again for your help.
     Well, I'm sorry that I don't know where is "bp-avatar-suggestions-version" option? Do you mean that I need to delete the BP-Avatar-Suggestion plugin totally? Or I need to edit the database or some settings at the backend panel?
     I tried several times and found it seems like that I can upload the image to server and can be found in the Media. But it can't display in the section below:
    
![avatar backend](https://cloud.githubusercontent.com/assets/10475793/13079753/a526174e-d4bd-11e5-93c1-c9a02ff46ae6.PNG)
So, what can I do now? Thanks.

**Comment by dandyxu** [comment]
Hi, imath
     I compared the links and found that when I check "BP Avatar Suggestions required post (do not edit or delete)", there is no draft post has been created. Maybe it's the issue where it is.
So, how can I fix that? Thanks.

**Comment by dandyxu** [comment]
![avatar attachment](https://cloud.githubusercontent.com/assets/10475793/13080890/851835c2-d4c2-11e5-9565-295e260d229c.PNG)
It seems like that when I add suggestion from Setting -> Avatar Suggestions, for avatar I uploaded, it doesn't assign to corresponding folder like "Uploaded To".

So, how can I re-assign these avatars to BP Avatar Suggestions required post (do not edit or delete)? Thanks.

**Comment by imath** [comment]
First: make sure to test on a* local environement*
Second: *back up your db*
Third if the post exist, check the table wp_options contains a line having an option name 'bp_avatar_suggestion_post_id' and the option value is the same than the post ID. 

If it's not the case simply completely delete the post, and remove the line of the wp_options table having an option name of "bp-avatar-suggestion-version". Once done go to the admin check the post exist, check the bp_avatar_suggestion_post is set with the post id.

Go to avatar admin, try to upload an avatar and check from the media library if it's attached to the post...

The error i saw looks like the post wasn't found.

imath.
http://profiles.wordpress.org/imath/

**Comment by dandyxu** [comment]
Hi, imath
     Great news!! The issue is fixed!! Thanks so much for your help and you're so kind! This problem confused me for more than one week and today it's finally fixed with your help! I'm so glad!
     However, I will write down all the process of issue and post to the WordPress.org Forum in order to help someone else might have the same issue with me.
     Anyway, do you have donation page? I'm not rich but I'm really want to appreciate your help and kindness.
     Thank you very much, imath.

**Comment by imath** [comment]
You're welcome, very happy it's fixed, thank you for the forum post and your donation :)

imath.
http://profiles.wordpress.org/imath/
