### ISSUE TITLE
Nothing happens upon "Insert into Post"

### ISSUE THREAD

**Issue by jcervantes28** [imath/bp-avatar-suggestions#4]
Love the idea behind this plugin and want to implement on my buddypress install.

I installed plugin, activated, followed the video, etc.

Went to add avatars in the plugin's settings within the buddypress settings, and when I add an avatar, choose an avatar and click "insert into post"

the image selection window goes white, nothing happens. I have to close the small image window to return to wp admin and there shows no added avatar.

Any help/solutions?

wp 3.9.1, bp 2.0

**Comment by imath** [comment]
this should be fixed by https://github.com/imath/bp-avatar-suggestions/commit/5f6136c1034226e1a477a8d41e31493dfc39f76a (1.2 branch)
